spring.application.name=restaurant

# Core 
spring.profiles.active=h2

# base endpoint configs
api-endpoint = api/v1

# Cookie SameSite configuration:  "Lax", "None" or "Strict"   
cookie-same-site =${COOKIE_SAME_SITE:Lax}

# CORS
frontend-domain = ${FRONTEND_DOMAIN:http://localhost:5173}

# jwt secrets
jwt-secret=${JWT_SECRET:0kuSAcoQ7qpnLOO92S2VCrkc8g2tiDrWgZ5V+lzYWqA=}

# SSL config (ones for localhost were created by mkcert)
server.ssl.key-store=${SSL_KEYSTORE_PATH:.certs/localhost+1.p12} 
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.port=8443

# Docker
spring.docker.compose.enabled=false